config/routes.rb
Rails.application.routes.draw do
  resources :anniversaries
  root :to => 'anniversaries#today'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anniversary.rb
class Anniversary < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/anniversaries_controller.rb
class AnniversariesController < ApplicationController
  before_action :set_anniversary, only: [:show, :edit, :update, :destroy]

  # GET /anniversaries
  # GET /anniversaries.json
  def index
    @anniversaries = Anniversary.all
  end

  # GET /anniversaries/1
  # GET /anniversaries/1.json
  def show
  end

  def today
    @todayEvents = Anniversary.where(month: Date.today.month, day: Date.today.day)
  end

  # GET /anniversaries/new
  def new
    @anniversary = Anniversary.new
  end

  # GET /anniversaries/1/edit
  def edit
  end

  # POST /anniversaries
  # POST /anniversaries.json
  def create
    @anniversary = Anniversary.new(anniversary_params)

    respond_to do |format|
      if @anniversary.save
        format.html { redirect_to @anniversary, notice: 'Anniversary was successfully created.' }
        format.json { render :show, status: :created, location: @anniversary }
      else
        format.html { render :new }
        format.json { render json: @anniversary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anniversaries/1
  # PATCH/PUT /anniversaries/1.json
  def update
    respond_to do |format|
      if @anniversary.update(anniversary_params)
        format.html { redirect_to @anniversary, notice: 'Anniversary was successfully updated.' }
        format.json { render :show, status: :ok, location: @anniversary }
      else
        format.html { render :edit }
        format.json { render json: @anniversary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anniversaries/1
  # DELETE /anniversaries/1.json
  def destroy
    @anniversary.destroy
    respond_to do |format|
      format.html { redirect_to anniversaries_url, notice: 'Anniversary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anniversary
      @anniversary = Anniversary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anniversary_params
      result=params.require(:anniversary).permit(:name, :date, :description)
      logger.debug result
      result["year"] =result["date(1i)"]
      result["month"] =result["date(2i)"]
      result["day"] =result["date(3i)"]
      return result
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/anniversaries_helper.rb
module AnniversariesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/anniversaries/_form.html.erb
<%= form_with(model: anniversary, local: true) do |form| %>
  <% if anniversary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anniversary.errors.count, "error") %> prohibited this anniversary from being saved:</h2>

      <ul>
      <% anniversary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :anniversary_name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :anniversary_date ,:start_year => 1900 %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :anniversary_description , :size => "50x3" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/anniversaries/edit.html.erb
<h1>Editing Anniversary</h1>

<%= render 'form', anniversary: @anniversary %>

<%= link_to 'Show', @anniversary %> |
<%= link_to 'Back', anniversaries_path %>

app/views/anniversaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anniversaries</h1>

<table class= "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Description</th>
      <th>Year</th>
      <th>Month</th>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anniversaries.each do |anniversary| %>
      <tr>
        <td><%= anniversary.name %></td>
        <td><%= anniversary.date %></td>
        <td><%= anniversary.description %></td>
        <td><%= anniversary.year %></td>
        <td><%= anniversary.month %></td>
        <td><%= anniversary.day %></td>
        <td><%= link_to 'Show', anniversary %></td>
        <td><%= link_to 'Edit', edit_anniversary_path(anniversary) %></td>
        <td><%= link_to 'Destroy', anniversary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anniversary', new_anniversary_path %>

app/views/anniversaries/new.html.erb
<h1>New Anniversary</h1>

<%= render 'form', anniversary: @anniversary %>

<%= link_to 'Back', anniversaries_path %>

app/views/anniversaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @anniversary.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @anniversary.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @anniversary.description %>
</p>

<p>
  <strong>Year:</strong>
  <%= @anniversary.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @anniversary.month %>
</p>

<p>
  <strong>Day:</strong>
  <%= @anniversary.day %>
</p>

<%= link_to 'Edit', edit_anniversary_path(@anniversary) %> |
<%= link_to 'Back', anniversaries_path %>

app/views/anniversaries/today.html.erb
<div>
<% if @todayEvents.count == 0 then %>
今日は何でもない日
<% else %>
    <% @todayEvents.each do |event| %>

<h1><%= link_to event.name, event  %></h1>

    <% end %>
<% end %>
</div>
<div>
<%= link_to 'New Anniversary', new_anniversary_path ,class: "btn btn-lg btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todayis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>